// Default theme - WhatsApp Style
const DEFAULT_THEME = {
  appName: 'Chat App',
  logoUrl: null,
  logoHeight: 40,
  sidebarBackgroundColor: '#FFFFFF',
  sidebarHeaderColor: '#008069',
  sidebarTextColor: '#111B21',
  sidebarHoverColor: '#F5F6F6',
  sidebarActiveColor: '#F0F2F5',
  sidebarBorderColor: '#E9EDEF',
  bottomNavBackgroundColor: '#FFFFFF',
  bottomNavActiveColor: '#008069',
  bottomNavInactiveColor: '#667781',
  bottomNavBorderColor: '#E9EDEF',
  headerBackgroundColor: '#008069',
  headerTextColor: '#FFFFFF',
  headerIconColor: '#FFFFFF',
  chatBackgroundColor: '#E5DDD5',
  chatBackgroundImage: null,
  senderBubbleColor: '#DCF8C6',
  senderTextColor: '#111B21',
  senderBubbleRadius: 8,
  receiverBubbleColor: '#FFFFFF',
  receiverTextColor: '#111B21',
  receiverBubbleRadius: 8,
  inputBackgroundColor: '#F0F2F5',
  inputTextColor: '#111B21',
  inputBorderColor: '#E9EDEF',
  inputPlaceholderColor: '#667781',
  sendButtonColor: '#008069',
  sendButtonIconColor: '#FFFFFF',
  unreadBadgeColor: '#25D366',
  avatarBackgroundColor: '#00A884',
  avatarTextColor: '#FFFFFF',
  timestampColor: '#667781',
  modalBackgroundColor: '#FFFFFF',
  modalTextColor: '#111B21',
  errorColor: '#ff4d4f',
  // Legacy fields for backward compatibility
  primaryColor: '#008069',
  secondaryColor: '#F0F2F5',
  accentColor: '#25D366',
  backgroundColor: '#FFFFFF',
  borderColor: '#E9EDEF',
  headerBackground: '#008069',
  headerText: '#FFFFFF',
  chatBubbleAdmin: '#DCF8C6',
  chatBubbleUser: '#FFFFFF',
  chatBubbleAdminText: '#111B21',
  chatBubbleUserText: '#111B21',
  messageFontSize: 14,
  messageBorderRadius: 8,
  bubbleStyle: 'rounded',
  blurEffect: 0.1,
  showAvatars: true,
  showReadStatus: true,
  enableTypingIndicator: true,
};

export const useTheme = () => {
  return { theme: DEFAULT_THEME, isLoading: false };
};

export default DEFAULT_THEME;